@extends('backend.layouts.master')

@section('content')
	<div class="container">
		<table class="table-calendar noselect" style="background-color: white;">
			<thead>
				<tr>
					<th>Pon</th>
					<th>Tor</th>
					<th>Sre</th>
					<th>Čet</th>
					<th>Pet</th>
					<th>Sob</th>
					<th>Ned</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><div>1</div></td>
					<td><div>2</div></td>
					<td><div>3</div></td>
					<td><div>4</div></td>
					<td><div>5</div></td>
					<td><div>6</div></td>
					<td><div>7</div></td>
				</tr>
				<tr>
					<td><div>1</div></td>
					<td><div>2</div></td>
					<td><div>3</div></td>
					<td><div>4</div></td>
					<td><div>5</div></td>
					<td><div>6</div></td>
					<td><div>7</div></td>
				</tr>
				<tr>
					<td><div>1</div></td>
					<td><div>2</div></td>
					<td><div>3</div></td>
					<td><div>4</div></td>
					<td><div>5</div></td>
					<td><div>6</div></td>
					<td><div>7</div></td>
				</tr>
				<tr>
					<td><div>1</div></td>
					<td><div>2</div></td>
					<td><div>3</div></td>
					<td><div>4</div></td>
					<td><div>5</div></td>
					<td><div>6</div></td>
					<td><div>7</div></td>
				</tr>

			</tbody>
		</table>
	</div>
@stop